---
title: "Section 3: Applied Concepts"
format: html
editor: visual
---

## 3.1: Class Prep 4

Read Sections 1.3 - 1.7 of Kearen Healy's Data Visualization: A Practical Introduction, found here. As you read, answer the following questions in just 1 to 2 sentences.

What is the difference between a colour's hue and a colour's intensity?

-   A color's hue is what is what most people refer to when describing a color (e.g. red, blue, orange, etc), while a color's intensity is refers to the vividness of the color.

Think of an example where you would want to use a sequential colour scale that's different from the one given in the text. Then, think of examples where you would use a diverging colour scale and an unordered colour scale.

-   When looking at the number of sales a salesperson makes on a team you would want to use a sequential color, because you want to highlight their performance over time (lighter colors could indicate less sales and darker could indicate more). For a diverging color scale, you could use a blue to red diverging color scale when trying to compare the sales person's performance to their monthly projection. If they are below their projection they could be blue, white for if they hit the projection, and reds for if they are above their target.

Some gestalt inferences take priority over others. Using Figure 1.21, give an example of a gestalt inference that takes priority over another one.

-   In the second row on the left, proximity seems to take priority over similarity, because they are all the differing shapes are aligned in a 3x3 matrix which makes the viewer perceive the shapes as all the same.

"Bar charts are better than Pie charts for visualizing a single categorical variable." Explain how results shown in Figure 1.23 support this claim.

-   The log error for pie charts was almost twice as high as bar charts. People had a much easier time identifying the smaller of two marked segments on the bar chart than the pie chart.

Suppose you have a scatterplot of height on the y-axis vs. weight on the x-axis for people born in Canada, Mexico, and the United States. You now want to explore whether the relationship is different for people born in the United States, people born in Canada, and people born in Mexico. Should you use different shapes to distinguish the three countries or should you use different colours? Explain using either Figure 1.24 or 1.25.

-   You should use different colors, because Figure 1.25 indicates for unordered categorical variables (like the US, Mexico, and Canada) colors are more effective for mapping data.

When might you use the left-side of Figure 1.27 to show the law school data? When might you use the right-side of Figure 1.27 to show the law school data?

-   In the left when the baseline is non-zero, you would use this graph to show the sharp decrease in law school enrollment. However, this can be miseleading because many people will not look at the scale on the y axis. You would use the right hand scale (when there is a zero baseline) to show the viewer the true number of enrollments.

Summary: What are two takeaways from Sections 1.3-1.7?

1.  For representing unordered categorical data in scatter plots, colors are better than shapes.
2.  Adding a baseline of 0 on a graph's y axis can make a huge difference in perception.

What is one question that you have about the reading?

-   Is there ever an appropriate time to make the base line of a y axis non zero?
